geopandas/contextily

contextily/tile.py
tests/test_ctx.py

If the tile is composed of multiple rasters and is not rectangular, you notice the saved raster is not correct.

BUG: fix width/height of saved raster files

---

contextily/__init__.py
contextily/place.py
contextily/plotting.py
tests/test_ctx.py

Opening PR to track evolution on #20. Before merging, the following needs to be completed:

[WIP] Initial stub on the road to address #20

---

contextily/__init__.py

This PR adds a `contextily.__version__` attribute, to have a minimal change to have a version.
Going forward, we may want to discuss this further:
- with the current version of this PR, when releasing that would mean updating the version tag in both `__init__.py` and `setup.py`
Alternatively, we can also do it in some other ways: https://packaging.python.org/guides/single-sourcing-package-version/
- Have a `contextily/_version.py` file that defines it and that is read by both placed (eg see https://github.com/uwescience/shablona)
- Use a tool like [bumpversion](https://github.com/peritus/bumpversion) to do this automatically
- Use a tool to do this automatically based on git tags (eg [versioneer](https://github.com/warner/python-versioneer))

Add __version__ attribute

---

setup.py

Right now https://pypi.org/project/contextily/ looks like:
The good news is the new PyPI (aka Warehouse) now supports Markdown for the description, so we can put README.md in there without conversion!
For more info and examples:
* https://pypi.org/project/markdown-description-example/
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example

Use README.md as description on PyPI

---

contextily/__init__.py
contextily/place.py
contextily/plotting.py
tests/test_ctx.py

This PR addresses #25 by adding `add_attribution` to the plotting module. By default, all plotting functionality will add an attribution statement equal to:
```python
("Map tiles by Stamen Design, under CC BY 3.0. "\
"Data by OpenStreetMap, under ODbL.")
```
but can be changed anywhere in the plotting methods across the library.

Adding attribution text

---

README.md
contextily/tile.py
requirements.txt
tests/test_ctx.py

This PR removed the use of cartopy's `merge_tiles` with a custom implementation
(related to https://github.com/darribas/contextily/issues/4 and https://github.com/SciTools/cartopy/issues/792).
It seemed this tile merging can actually rather easily be done, using some of the features of `mercantile` (which is already used to calculate the web tile x and y numbers given the zoom and bounds), and using some assumptions about the fact that we only deal with web map tiles (all rectangular equal sized images for a given extent).
Just pushing this now to show the implementation. I didn't yet look at or update the tests. 
I actually expect the tests to be failing, as while doing this, I discovered that there is a bug in the current implementation (we are overlaying the tiles with one pixel …

Re-implementation of tile merging based on mercantile

---

README.md
contextily/tile.py
requirements.txt

Because it is not needed + to overcome pandas API change in 0.24.0
to return scalar instead of 1-element array
Noticed when I was running the tests for the other PR using pandas master. Related change in pandas is https://github.com/pandas-dev/pandas/pull/23801

COMPAT: use numpy searchsorted

---

requirements-dev.txt
requirements.txt

Pytest is only a testing (dev) requirement, so is not needed to have in the hard requirements.

Move pytest to dev requirements

---

contextily/tile.py

Tiny refactor to move request to image conversion outside of `bounds2img`.

Move request handling outside of bounds2img function

---

.travis.yml
requirements.txt

Addressing #62 (see also pysal/splot#48)
Since there is no more support for `Python2`, is there a specific reason to perform TravisCI environment builds with `Miniconda2`? This PR addresses that issue and includes the new `conda` feature:
`- conda config --set channel_priority strict`.

use Miniconda3

---

contextily/tile.py

This addresses #64 by introducing the correct order for bounds when passing to `_calculate_zoom` in `bounds2img` and `bounds2raster`

Issuing bug fix for #64

---

contextily/tile.py
contextily/tile_providers.py
tests/test_providers.py

Closes https://github.com/darribas/contextily/issues/60

Use standard urls with {x} instead of 'tileX'  + deprecate old format

---

contextily/plotting.py
tests/test_ctx.py

Opening this for discussion: in my original implementation (http://geopandas.readthedocs.io/en/latest/gallery/plotting_basemap_background.html#contextily-helper-function) I reset the axis limits to the original ones when the `ax` is passed to the function. 
One reason to do this: the extent of the figure does not depend on the zoom level (on how many tiles are merged).
Closes https://github.com/darribas/contextily/issues/45

add_basemap: keep original axis limits of figure

---

README.md
ci/travis/36-minimal.yaml
ci/travis/37-latest-conda-forge.yaml
contextily/tile.py
requirements.txt

@darribas @ljwolf here the version based on joblib, alternative for https://github.com/darribas/contextily/pull/57, https://github.com/darribas/contextily/pull/68, or https://github.com/darribas/contextily/pull/79
Within a session, you can do `contextily.tile.memory.clear()` to empty the cache.
With the current version, it is not possible to do something like:
```
import contextily
import joblib
contextily.tile.memory = joblib.Memory('/my/custom/dir')
```
to be able to keep the cache alive across sessions (currently I delete the temporary directory at the end of every python session). 
The reason for that is because it is decorating the `_fetch_tile` function, and overwriting the memory object is not changing the decorated function .. (probably this could be avoided with some effort, not …

ENH: use joblib for caching result of fetch_tile

---

contextily/plotting.py

This provides a hack to wrap the text of the attribution.

ENH: wrap attribution text

---

contextily/_providers.py
contextily/place.py
contextily/plotting.py
scripts/parse_leaflet_providers.py
tests/test_ctx.py

Work in progress, still needs to add tests and update docs. And was trying out if I could "auto wrap" the text, but not yet much success (https://matplotlib.org/3.1.1/gallery/text_labels_and_annotations/autowrap.html)

ENH: use attribution from provider if available

---

contextily/plotting.py
tests/test_ctx.py

This is a proposal to change the return value of `add_basemap` from `ax` to the Image artist created by the function. Some reasoning (as it is a breaking change):
- returning `ax` is useless (you already pass the ax objects, so you already have this object named) and also potentially confusing (is this a different ax than the one passed in?)
- sometimes it can be useful to have the matplotlib artist object that was created (eg for eg for adding a colorbar for it, although that is not relevant for tile backgrounds, but there might be other things as well). 
You can get this eg by inspecting `ax.get_children()`, but that is always a bit tricky. Having it returned from the function is easier (and in 99% of the cases the user can simply ignore this return value anyway). 
- at some point this …

API: change add_basemap to not return the received ax object

---

examples/plot_map.py
tests/test_ctx.py

It looks like `contextily.calculate_zoom` was changed to a private function, so I'm updating the example to work again.
BTW, contextily is so nice @darribas :)

updates example to work with renamed function

---

contextily/plotting.py

1. On Python 3.5 the comma at the end of the constructor raises a `SyntaxError`.
2. The data type of the '**extra_imshow_args` is not dict but undefined or various or just empty.
3. Shouldn't it be named `extra_imshow_kwargs` as it collects "keyword arguments" and not unnamed "arguments". But this is not very important, so I did not changed by now. I can change it if you agree.

Fix syntax error on Python 3.5 and wrong data type

---

README.md

Towards #37 this adds instructions for how to install the release candidate to get `add_basemap` and other functionality.

added instructions to install the release candidate

---

contextily/tile.py
contextily/tile_providers.py
tests/test_providers.py

This addresses points discussed in #90 by adding:
1. a new argument `source` that supplants `url`. 
2. a deprecation warning whenever `url` is provided to either `bounds2img` or `bounds2raster`
3. a deprecation warning whenever one of the `contextily.tile_providers` strings is accessed
For some reason on my local computer (python 3.7.6) I do not see the warning text, despite verifying that the conditional in `tile_providers.py` is evaluated & the replacement string is returned correctly. Is this just my install? or do others not see the warning text? 
Closes #90

Deprecate URL option in favor of source argument

---

contextily/plotting.py
tests/test_ctx.py

This adds support for memory-efficient, window-based reading of local files when `reset_extent=True`, addressing #86, and also fixes #100 by squeezing 1-band rasters to a two-dimensional image before plotting.

ENH: support reading window from local files (#86)

---

docs/_static/css/custom.css
docs/_templates/docs-sidebar.html
docs/_templates/layout.html
docs/conf.py

This is what I currently need for getting http://jorisvandenbossche.github.io/example-pandas-docs/contextily/index.html
Some of the custom css should not be needed if we can improve the ability to override eg the highlight color in the upstream theme. But it's good to experiment with this to see how we can improve the extendibility of the theme.

Use customized version of the pydata-sphinx-theme

---

contextily/tile.py
tests/test_ctx.py

Closes https://github.com/darribas/contextily/issues/46
cc @uvchik 
For now, just added a function that the user can call as (and didn't add it in other places, like add_basemap):
```
contextily.set_cache_dir("/path/to/local/cache/")
```
I used `set_cache_dir`, but @uvchik made the suggestion to call it `use_cache` :
> I would name it `use_cache` because one has to execute it every time one wants to plot. For me 'set' indicates, that I have to execute it once. But I am not a native speaker and I am open to other names.
(note that this "every time one wants to plot is not "for every `add_basemap()` call", you only need to do it once in your python session (eg put it at the beginning of your script or notebook), but it is true that you still need to do it every time once per session, it's …

ENH: option to set cache dir to permanent directory

---

docs/conf.py
docs/index.rst

This ensures the notebooks are added to the docs (and thus show up on https://contextily.readthedocs.io/en/latest/)

Add notebooks to the docs

---

README.md
setup.py

This PR clarifies the version of Python 3 required for running `contextily`. It also updates the `conf.py` to reflect Python 3.6 or above is required.
Fix #149

Require Python 3.6 as minimum version (#149)

---

notebooks/working_with_local_files.ipynb

Fixes a small inconsistency in the docs where the text and variable names were about Sao Paolo but the data used was for Cape Town.

Use Cape Town consistently in description and variable names

---

contextily/tile.py

Depending on format, datasets that have been written need to be closed before they are complete, so this is safer. A future version of rasterio will require that datasets passed to WarpedVRT be opened in read-only mode. Also, using numpy.moveaxis so that we only call mraster.write once.

Close and reopen memfile dataset before WarpedVRT

---

contextily/place.py
contextily/plotting.py

Add random user ID for Nominatim and allow arbitrary geocoder

---

docs/index.rst

First of all, thank you for creating and maintaining this handy package! I added some examples to showcase the `Place`API. Let me know whether this is anywhere close to what you had in mind! Feedback and suggestions always appreciated :–)

Examples added in the places_guide notebook (#143)

---

docs/_static/css/custom.css
docs/_templates/docs-sidebar.html
docs/_templates/layout.html
docs/environment.yml
docs/index.rst

This updates for the latest version of the theme (eg we were still using the variable names of the unreleased version, and those were changed). 
Further, it also makes use of some new features.
One of them is that we can now have **captions** in the sidebar. @darribas I seem to remember that you initially wanted this when we made the docs (but at that time I said that the theme didn't yet support it, but would so in the future). I am only not sure what would be useful distinctions. What I tried out now gives:
Do we want something like that? (right now, the "reference guide" is a bit duplicated between the caption and the actual link ..)

DOC: captions + update for latest pydata-sphinx-theme

---

tests/test_ctx.py
tests/test_providers.py

Some changes happened in the upstream (geocoding/stamen) causing failures on CI. I've checked the new returns and they're okay, so just updating expected values to match.
I have also split one long test function into several smaller.

TST: update tests to match the return

---

tests/conftest.py
tests/test_ctx.py
tests/test_providers.py

I'm sure there's a possibility that some tests don't _need_ to use the network, but I'm not familiar enough with them to decide that. This just adds the marker so they can be skipped. There are 12 that use the network and 7 pass without the network.
Fixes #123.

Mark tests that require the network.

---

contextily/plotting.py
tests/test_ctx.py

Enabling passing a string from `source` to `query_name` to fetch the `TileProvider` in a more flexible way as we have in explore in GeoPandas.
Closes #190

ENH: expose query_name in source

---

contextily/tile.py
tests/test_ctx.py

For maps with large aspect ratio, contextily downloads tiles as if the map was as small as the smallest dimension. It should base the zoom level on the dimension that's a larger extent.
I discovered this bug when my server died attempting to render the following blue line on a map:
https://sondemaps.lectrobox.com/seattle/2023/4/13-17-47.64048--123.95468.jpg
This script has run fine for months, but in today's dataset the blue line coincidentally was almost perfectly horizontal. Therefore, the latitude extent of the map was very small, and because contextily uses the max of the two zoom levels, it attempted to download over a million zoomlevel 19 tiles from OSM.

Fix bug in auto computation of zoom levels

---

contextily/tile.py
tests/test_ctx.py

This pull request is a fix for https://github.com/geopandas/contextily/issues/215 
I have added support for parallel tile downloads in the bounds2raster and bounds2img functions. It gives some quite significant speed improvements, with minor changes to the code. I wasn't sure were to put `max_num_parallel_tile_downloads = 32`, so for now it is on line 227 in `tile.py` (i.e., inside the bounds2img function code). Let me know if there is anything you would like to have changed. 
Thanks for an awesome package btw.! :smiley:

Added support for parallel tile downloads and control of cache

---

contextily/place.py
contextily/plotting.py
examples/plot_map.py
notebooks/working_with_local_files.ipynb
tests/test_cx.py
tests/test_providers.py

This PR addresses the inconsistent import alias, instead of contextily being imported as `ctx` or `cx` it is now only imported as `cx`. This is in line with the [GeoPandas documentation](https://geopandas.org/en/stable/gallery/plotting_basemap_background.html).

Fix inconsistency in import alias

---

contextily/tile.py
tests/test_cx.py

moving image opening to the retryer in hope that it could resolve rare occasions of `UnidentifiedImageError` popping up. Reported in https://github.com/networkx/networkx/issues/7301 and seen once in our CI ([here](https://github.com/geopandas/contextily/actions/runs/7909639251/job/21591004622)). I wasn't able to reproduce the issue locally in any form so I am not sure if it will fix it but it is the only thing I could think of.
To get a better control of retries, we should also probably expose  `wait`, `max_retries`, `n_connections` and `use_cache` on `add_basemap` level, not only in `bounds2img` but I'll do that separately.

expand retryer to include image reading

---

contextily/tile.py

Using Contextily in a managed serverless environment removes the tmp directory before `atexit` fires, which results in the following error. Which, I wager means it can't find the indicated directory to delete. 
```
Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/contextily/tile.py", line 61, in _clear_cache
shutil.rmtree(tmpdir)
File "/layers/google.python.runtime/python/lib/python3.11/shutil.py", line 742, in rmtree
onerror(os.lstat, path, sys.exc_info())
File "/layers/google.python.runtime/python/lib/python3.11/shutil.py", line 740, in rmtree
orig_st = os.lstat(path, dir_fd=dir_fd) 
```
I can put our invocation behind a try-catch, or otherwise ignore this error, but an upstream patch would be preferable. 
Thanks!

Ignore rmtree errors for serverless environments

---

tests/test_providers.py

This is tested in xyzservices and just got out of sync. No need to duplicate.

TST: remove callable test

---

contextily/tile.py

BUG: replace os.wait with time.sleep

---

contextily/tile.py

Fixes #247
Changed:
* made sure all `HTTPError`s are captured and retried
* included the last error/reason message when max_retries is reached
The code in this contribution catches all `HTTPError`s and therefore makes it impossible that the code continue with `None` in the `arrays` list. This used to cause varying errors related to `None`, depending on whether the first in the `arrays` list was `None` or not, or any of the others. By capturing all HTTPErrors, the code is redirected to retrying instead of that the `_retryer()` function returns None. After `max_retries` is reached, the user now gets a informative error message. The format of the message is based on what `request.raise_for_status()` would return.
The current code proves useful, these were the error messages during the manual …

improve stability of ctx.add_basemap()

---

tests/test_cx.py

HOT tiles tend to update frequently, which is breaking our CI. This PR switches to CartoDB Positron at most relevant places, which should be more stable.

TST: make testing more stable

---

contextily/plotting.py
tests/test_cx.py

Closes #251 
Using `aspect=ax.get_aspect()` fixes the behaviour reported in #251 and avoid changing the aspect of the axis if it is other than equal.
What I am not certain is whether we want to do this as it means that resulting pixels are not square, distorting the image. But that is ultimately a responsibility of a user and this way we give them a chance to affect the aspect as until now, we always enforce equal aspect.
The only relevant change is on line 204, the rest is linting.

BUG: do not change the aspect of the axis
